travis:
  secure:
    BINSTAR_TOKEN: OP9Fifl/YsbMM+Q8B9xdeUM0cySjaqQjI565I3NMaQfY978zx2iboq/eRhR7GGGKv45hp8D9wQsk5C2js4UlUIp/UwonrKA6X313NcrAkGNlaOVAAg0mAGjCD+yRxFlYZDOKPC6ksFRbADDjrpirrNML6LqyRmkuzM3mjkWIKm5mLepGhzIm7r0cuQaTpwD3mjCqPZQnzfXomHr0AZlKrj4v7cs189svNOq0CZDyomEw1hKHmuyQJANvJeEboJG6BJPc0a3i/s81TEKKHF35z7OuhZBm9k5TPLBGoCEI7HvBI7bAySQzZPdSgsue44+CCsnZnpOk3Ou3MnKqB5LTrc0pulx9Cxpxe77VF3RlZlRTsP91P5aYjlDzJQw4QhCS0hpr1TYCHNmlptg5TV1BC54g9ZYvlSjVLMq2dOfVQ/T/s43lJoH1ycwmoyoGe/oeUOhsZqIcL4FuMFPYiuRi0P/6Hpu0/mO1sAb+zkj4NvQNpFFW6BhWQNqyot44HFuYQKOIMJCF6Z0yO25gOJ7s2SktnuUMISGnLG/pXeu2jQ3XELf9LCSvsdlCfCDvMX0ZSa3GBVb6qKnbD8mzNhR29Ixrd9aWsGSnx3vwG4sa0thCXVIwqPqo2ljjf/3D7NcKoLqtSdkuuSOc39jikOfUGZQofhIZnVh9Nb1MISmmKuw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
