travis:
  secure:
    BINSTAR_TOKEN: TbWFTurQWZSKEIUisBnN/oGbGFBj8hQU1we2fmjIRNJgm7F0e8iR0v9mnSav57WL99BzTSU4O7hjSsY0shM3bPIadE+17C6xkvrYsG4j1K8Tf5ORjq9jLj7WUWoJdHkm5rpkLjlYK557Fd4560lulQSHOhk2Yi/mY79YhPJom2CHH19lC5tQB6/61R+O+7IececmabYYFnTVRInUS6Xe3lHyT94aSOFjaUbO7WSq6Xf2pPah0U1b38E3cUjqikOnkqdD29TZfNoX+Juq1oOCCY5xsXGqUOZj6EPUXTCaqlqw9hwNRtCcyT8oszGRSCBG58NpWjLOutAYPtgcU1LQ8iJaAG2d9/0R9L8mNT6nS+Fi8mZZ8cd89n+1hVwUyg06Lv7TEmy/lEhxEz/Q3E3TLoSQldX9tUgRAVO2R2sAbg9vsFikl2YaMPci3oFXOnqR/H3H5Vo6N7tRrN98N5fy1iXw3JV3RlLRAdl4LAYvjH7yTEcYmm6dQILlnDzSaIIK5dnpH7AtBfKsbZjgPUjfwgnDB96rbNnPSJo3he7hg3wkG1/DSrHKwTJSDSDOI+cr3lLCk4TnUqeT2zCEyOf1VmpiRzmRcpOsNbdYh//CtZ6lW5ibnMWNWlm+G5KQrDMlVgxB3YDkPmshklQjW77vfPhdp87NvE/YkS0ZxD6sdjo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
